Repository quocthangK64/MOSD.20221.Group09, pull requests merged in 2023-01, with the labels that each got.

#7 Create main class for Travelwala
  Frontend/src/App.css
  Frontend/src/App.js
  Frontend/src/index.css
  Frontend/src/index.js
Labels: enhancement

#20 Create Newsletter
  Frontend/src/components/NewsLetter/beach.webp
  Frontend/src/components/NewsLetter/details.jsx
  Frontend/src/components/NewsLetter/index.jsx
  Frontend/src/components/NewsLetter/sideImage.jsx
Labels: enhancement

#19 Create DateTimeUtil để kiểm tra ngày giờ
  Frontend/src/utils/DateTimeUtils.ts
Labels: enhancement

#13 create footer component and some miscellaneous
  Frontend/src/components/Footer.js
  Frontend/src/components/WalaTextField.js
  Frontend/src/styles/Footer.css
  Frontend/src/styles/theme.js
Labels: enhancement

#22 Create common component Navbar
  Frontend/src/components/Navbar.js
Labels: enhancement

#21 Tạo entity Passenger và PassengerRepository
  Backend/src/main/java/com/ict/group09/travelwala/passenger/entity/Passenger.java
Labels: enhancement

#17 create PassengerController class
  Backend/src/main/java/com/ict/group09/travelwala/passenger/controller/PassengerController.java
  Backend/src/main/java/com/ict/group09/travelwala/passenger/service/PassengerService.java
Labels: enhancement

#16 Tạo Request&Response cho passenger
  Backend/src/main/java/com/ict/group09/travelwala/model/request/PassengerRequest.java
  Backend/src/main/java/com/ict/group09/travelwala/model/response/PassengerResponse.java
Labels: enhancement

#24 Tạo entity Passenger và PassengerRepository
  Backend/src/main/java/com/ict/group09/travelwala/model/request/PassengerRequest.java
  Backend/src/main/java/com/ict/group09/travelwala/model/response/PassengerResponse.java
  Backend/src/main/java/com/ict/group09/travelwala/passenger/repository/PassengerRepository.java
Labels: enhancement

#36 Home screen components
  Frontend/src/pages/home/Home.jsx
  Frontend/src/pages/home/components/BasicDatePicker.js
  Frontend/src/pages/home/components/FlightSearchBox.css
  Frontend/src/pages/home/components/FlightSearchBox.js
  Frontend/src/pages/home/components/LocationBox.js
Labels: enhancement

#40 add some aditional components to the homescreen
  Frontend/src/pages/home/components/Passengers.js
  Frontend/src/pages/home/components/SimplePopper.js
  Frontend/src/pages/home/components/SwitchSearch.js
Labels: enhancement

#34 Pull request for passenger service and module flight
  Backend/src/main/java/com/ict/group09/travelwala/flight/controller/FlightController.java
  Backend/src/main/java/com/ict/group09/travelwala/passenger/service/PassengerService.java
  Backend/src/main/java/com/ict/group09/travelwala/passenger/service/impl/PassengerServiceImpl.java
Labels: bug, enhancement

#37 Create mapper for Passenger
  Backend/src/main/java/com/ict/group09/travelwala/mapstruct/mappers/PassengerMapper.java
Labels: enhancement

#44 Create APIs for module Flight
  Backend/src/main/java/com/ict/group09/travelwala/flight/controller/FlightController.java
  Backend/src/main/java/com/ict/group09/travelwala/flight/service/FlightService.java
  Backend/src/main/java/com/ict/group09/travelwala/flight/service/IAvailableSeatsCheck.java
  Backend/src/main/java/com/ict/group09/travelwala/flight/service/ICalculateFlightFare.java
  Backend/src/main/java/com/ict/group09/travelwala/flight/service/IOccupySeats.java
  Backend/src/main/java/com/ict/group09/travelwala/flight/service/impl/FlightServiceImpl.java
Labels: enhancement

#39 Added ERD and database schema
  Design/database/erd.png
  Design/database/schema.png
Labels: documentation

#42 Tạo các entity và repo cho module flight
  Backend/src/main/java/com/ict/group09/travelwala/flight/entity/Airline.java
  Backend/src/main/java/com/ict/group09/travelwala/flight/entity/Airport.java
  Backend/src/main/java/com/ict/group09/travelwala/flight/entity/Flight.java
  Backend/src/main/java/com/ict/group09/travelwala/flight/entity/Plane.java
  Backend/src/main/java/com/ict/group09/travelwala/flight/repository/AirlineRepository.java
  Backend/src/main/java/com/ict/group09/travelwala/flight/repository/AirportRepository.java
  Backend/src/main/java/com/ict/group09/travelwala/flight/repository/FlightRepository.java
  Backend/src/main/java/com/ict/group09/travelwala/flight/repository/PlaneRepository.java
  Backend/src/main/java/com/ict/group09/travelwala/flight/repository/impl/FlightRepositoryImpl.java
Labels: enhancement

#45 initiate redux and set up for later use of api
  Frontend/src/hooks/useNavigateSearch.js
  Frontend/src/redux/actions.js
  Frontend/src/redux/booking/BookingSlice.ts
  Frontend/src/redux/booking/types.ts
  Frontend/src/redux/constants.js
  Frontend/src/redux/reducer.js
  Frontend/src/redux/selectors.js
  Frontend/src/redux/store.ts
Labels: enhancement

#67 Fix Home page not displaying due to Routing problem
  Frontend/src/pages/index.js
Labels: enhancement

#43 Create response and request for flight
  Backend/src/main/java/com/ict/group09/travelwala/flight/model/request/FlightCriteria.java
  Backend/src/main/java/com/ict/group09/travelwala/flight/model/request/FlightRequest.java
  Backend/src/main/java/com/ict/group09/travelwala/flight/model/response/AirlineResponse.java
  Backend/src/main/java/com/ict/group09/travelwala/flight/model/response/AirportResponse.java
  Backend/src/main/java/com/ict/group09/travelwala/flight/model/response/PlaneResponse.java
  Backend/src/main/java/com/ict/group09/travelwala/flight/model/response/SearchFlightResponse.java
  Backend/src/main/java/com/ict/group09/travelwala/model/response/FlightResponse.java
Labels: enhancement

#75 Add flight exception
  Backend/src/main/java/com/ict/group09/travelwala/flight/exception/FlightLocationException.java
  Backend/src/main/java/com/ict/group09/travelwala/flight/exception/FlightTimeException.java
  Backend/src/main/java/com/ict/group09/travelwala/flight/exception/PassengerException.java
Labels: enhancement

#38 Create controller, config and dtos for feature register/ login
  Backend/src/main/java/com/ict/group09/travelwala/sercurity/config/AppConfig.java
  Backend/src/main/java/com/ict/group09/travelwala/sercurity/controller/LoginController.java
  Backend/src/main/java/com/ict/group09/travelwala/sercurity/controller/RegistrationController.java
  Backend/src/main/java/com/ict/group09/travelwala/sercurity/controller/UserController.java
  Backend/src/main/java/com/ict/group09/travelwala/sercurity/dto/AppUserRegisterRequest.java
  Backend/src/main/java/com/ict/group09/travelwala/sercurity/dto/AppUserRegisterResponse.java
  Backend/src/main/java/com/ict/group09/travelwala/sercurity/dto/LoginRequest.java
  Backend/src/main/java/com/ict/group09/travelwala/sercurity/dto/LoginResponse.java
  Backend/src/main/java/com/ict/group09/travelwala/sercurity/dto/UserLoginResponse.java
  Backend/src/main/java/com/ict/group09/travelwala/sercurity/dto/oauth2/FacebookOAuth2UserInfo.java
  Backend/src/main/java/com/ict/group09/travelwala/sercurity/dto/oauth2/GoogleOAuth2UserInfo.java
  Backend/src/main/java/com/ict/group09/travelwala/sercurity/dto/oauth2/OAuth2UserInfo.java
  Backend/src/main/java/com/ict/group09/travelwala/sercurity/dto/oauth2/OAuth2UserInfoFactory.java
  Backend/src/main/java/com/ict/group09/travelwala/sercurity/entity/AppUser.java
  Backend/src/main/java/com/ict/group09/travelwala/sercurity/entity/AppUserRole.java
  Backend/src/main/java/com/ict/group09/travelwala/sercurity/entity/ConfirmationToken.java
  Backend/src/main/java/com/ict/group09/travelwala/sercurity/entity/Provider.java
  Backend/src/main/java/com/ict/group09/travelwala/sercurity/exception/OAuth2AuthenticationProcessingException.java
  Backend/src/main/java/com/ict/group09/travelwala/sercurity/exception/UserAlreadyExistException.java
  Backend/src/main/java/com/ict/group09/travelwala/sercurity/filter/AuthenticationFilter.java
  Backend/src/main/java/com/ict/group09/travelwala/sercurity/filter/AuthorizationFilter.java
  Backend/src/main/java/com/ict/group09/travelwala/sercurity/repo/AppUserRepo.java
  Backend/src/main/java/com/ict/group09/travelwala/sercurity/security/AuthenticationSuccessHandler.java
  Backend/src/main/java/com/ict/group09/travelwala/sercurity/security/SecurityConfiguration.java
  Backend/src/main/java/com/ict/group09/travelwala/sercurity/service/AppUserService.java
  Backend/src/main/java/com/ict/group09/travelwala/sercurity/service/AppUserServiceImpl.java
  Backend/src/main/java/com/ict/group09/travelwala/sercurity/service/confirmation_token/ConfirmationService.java
  Backend/src/main/java/com/ict/group09/travelwala/sercurity/service/confirmation_token/ConfirmationServiceInterface.java
  Backend/src/main/java/com/ict/group09/travelwala/sercurity/service/confirmation_token/ConfirmationTokenRepo.java
  Backend/src/main/java/com/ict/group09/travelwala/sercurity/service/email/EmailServiceInterface.java
  Backend/src/main/java/com/ict/group09/travelwala/sercurity/service/email/MailServiceImpl.java
  Backend/src/main/java/com/ict/group09/travelwala/sercurity/service/email/SpringMailConfig.java
  Backend/src/main/java/com/ict/group09/travelwala/sercurity/service/loginToken/LoginConfig.java
  Backend/src/main/java/com/ict/group09/travelwala/sercurity/service/loginToken/LoginToken.java
  Backend/src/main/java/com/ict/group09/travelwala/sercurity/service/loginToken/LoginTokenService.java
  Backend/src/main/java/com/ict/group09/travelwala/sercurity/service/loginToken/LoginTokenServiceImpl.java
Labels: enhancement

#69 Calling login api
  Frontend/src/api/signin/SignInService.ts
  Frontend/src/api/signin/SignInService.types.ts
Labels: enhancement

#65 Create Redux for Global States
  Frontend/src/store/Context.js
  Frontend/src/store/Provider.js
  Frontend/src/store/actions.js
  Frontend/src/store/hooks.js
  Frontend/src/store/index.js
  Frontend/src/store/reducer.js
Labels: enhancement

#71 Create enum for module Ticket
  Backend/src/main/java/com/ict/group09/travelwala/ticket/enumeration/TicketEnum.java
Labels: enhancement

#70 Create entity for Contact
  Backend/src/main/java/com/ict/group09/travelwala/contact/entity/Contact.java
Labels: enhancement

#72 Create Ticket Entity
  Backend/src/main/java/com/ict/group09/travelwala/ticket/entity/Ticket.java
Labels: enhancement

#73 create Service for module Ticket
  Backend/src/main/java/com/ict/group09/travelwala/ticket/service/ICreateTicket.java
  Backend/src/main/java/com/ict/group09/travelwala/ticket/service/impl/TicketServiceImpl.java
Labels: enhancement

#74 create Service for module Contact
  Backend/src/main/java/com/ict/group09/travelwala/contact/service/ISaveContact.java
  Backend/src/main/java/com/ict/group09/travelwala/contact/service/impl/ContactServiceImpl.java
Labels: enhancement

#78 Create Contact and Ticket Request/Respond
  Backend/src/main/java/com/ict/group09/travelwala/model/request/ContactRequest.java
  Backend/src/main/java/com/ict/group09/travelwala/model/response/ContactResponse.java
  Backend/src/main/java/com/ict/group09/travelwala/model/response/CreateTicketResponse.java
Labels: enhancement

#76 create a list of flights
  Frontend/src/pages/listflights/ListFlight.tsx
  Frontend/src/pages/listflights/components/FlightSearchBar.css
  Frontend/src/pages/listflights/components/FlightSearchBar.js
  Frontend/src/pages/listflights/components/flight-cart/FlightCart.tsx
  Frontend/src/pages/listflights/components/flight-cart/flight-detail/FlightDetail.tsx
  Frontend/src/pages/listflights/components/tablelistflight/FlightItem/FlightItem.tsx
  Frontend/src/pages/listflights/components/tablelistflight/TableListFlight.styles.ts
  Frontend/src/pages/listflights/components/tablelistflight/TableListFlights.tsx
Labels: enhancement

#81 Tạo API communicator cho module flights
  Frontend/src/api/flight/FlightService.ts
  Frontend/src/api/flight/FlightService.types.ts
Labels: enhancement

#63 Added data modeling part in SDD
  Design/sdd/SDD.docx
Labels: documentation

#79 Add Common
  Backend/src/main/java/com/ict/group09/travelwala/common/enumeration/seatclass/SeatClassEnum.java
  Backend/src/main/java/com/ict/group09/travelwala/common/exception/ApiErrorHandler.java
  Backend/src/main/java/com/ict/group09/travelwala/common/exception/RecordNotFoundException.java
  Backend/src/main/java/com/ict/group09/travelwala/common/exception/WalaErrorResponse.java
  Backend/src/main/java/com/ict/group09/travelwala/common/exception/WalaException.java
  Backend/src/main/java/com/ict/group09/travelwala/common/repository/WalaCrudRepository.java
  Backend/src/main/java/com/ict/group09/travelwala/common/repository/WalaRepository.java
  Backend/src/main/java/com/ict/group09/travelwala/common/repository/WalaRepositoryImpl.java
Labels: enhancement

#80 Create package travelwala.mapstruct.mappers
  Backend/src/main/java/com/ict/group09/travelwala/mapstruct/mappers/ContactMapper.java
Labels: enhancement
